<?php

return [
    'kg' => 'Kilogram (kg)',
    'g' => 'Gram (g)',
    'mg' => 'Milligram (mg)',
    'lb' => 'Pound (lb)',
    'oz' => 'Ounce (oz)',
    'ton' => 'Ton',
    'l' => 'Liter (l)',
    'ml' => 'Milliliter (ml)',
    'kl' => 'Kiloliter (kl)',
    'm' => 'Meter (m)',
    'cm' => 'Centimeter (cm)',
    'mm' => 'Millimeter (mm)',
    'km' => 'Kilometer (km)',
    'ft' => 'Foot (ft)',
    'in' => 'Inch (in)',
    'yd' => 'Yard (yd)',
    'pcs' => 'Piece (pcs)',
    'box' => 'Box',
    'dozen' => 'Dozen',
    'bag' => 'Bag',
    'set' => 'Set',
    'bundle' => 'Bundle',
    'pack' => 'Pack',
    'roll' => 'Roll',
    'pair' => 'Pair',
    'sheet' => 'Sheet',
    'carton' => 'Carton',
    'can' => 'Can',
    'bottle' => 'Bottle',
    'jar' => 'Jar',
    'tube' => 'Tube',
    'case' => 'Case',
    'ream' => 'Ream',
    'pallet' => 'Pallet',
    'strip' => 'Strip',
    'unit' => 'Unit',
    'sqft' => 'Square Foot (sqft)',
    'sqm' => 'Square Meter (sqm)',
    'sqin' => 'Square Inch (sqin)',
    'cubicm' => 'Cubic Meter',
    'cubicft' => 'Cubic Foot',
];
